### ISSUE TITLE
undefined reference to `iotc_bsp_io_net_socket_connect' when make flash (CA-41)

### ISSUE THREAD

**Issue by wanyu0002** [espressif/esp-google-iot#10]
Follow the steps and try to flash to the ESP32, find this issue.
![LD](https://user-images.githubusercontent.com/25152225/70705167-794c1b80-1d0e-11ea-9af9-f995c5a1101f.PNG)

**Comment by jojoqool** [comment]
Hi, I find this issue too, did u fix it?
