### ISSUE TITLE
Update the google embedded C parts to current 1.0.2 version (CA-49)

### ISSUE THREAD

**Issue by nikojarvinen** [espressif/esp-google-iot#13]
There are updates to the underlying google embedded C library. Would it be possible to get it updated? I tried doing the update but got stuck on:

/home/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/googleIotCore/libgoogleIotCore.a(iotc_io_net_layer.c.obj):(.literal.iotc_io_net_layer_connect+0x8): undefined reference to `iotc_bsp_io_net_socket_connect'
/home/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/googleIotCore/libgoogleIotCore.a(iotc_io_net_layer.c.obj): in function `iotc_io_net_layer_connect':
/home/esp/rb3/build/../components/googleIotCore/iot-device-sdk-embedded-c/src/libiotc/io/net/iotc_io_net_layer.c:62: undefined reference to `iotc_bsp_io_net_socket_connect'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by kangbudz** [comment]
i solve this issue by add iotc_bsp_io_net_socket_connect into port of freertos posix (in port folder of component ).
you could try it

**Comment by sarasini** [comment]
I also have this issue

**Comment by sarasini** [comment]
@kangbudz can you better explain how you solved the issue? thanks!

**Comment by kangbudz** [comment]
hello @sarasini 
Sorry for maybe late reply.
in esp-idf google-iot-sdk component folder, there is 2 folder inside :
- iot-device-sdk-embedded-c
- port 

port folder is part of ESP-IDF freertos posix port of iot-device-sdk-embedded-c.
inside this port folder, open source file and file  "iotc_bsp_io_net_posix.c"
and add this function "iotc_bsp_io_net_socket_connect" into it.
this function itself you can find inside iot-device-sdk-embedded-c for posix.
may this help you

`iotc_bsp_io_net_state_t iotc_bsp_io_net_socket_connect(
    iotc_bsp_socket_t* iotc_socket, const char* host, uint16_t port,
    iotc_bsp_socket_type_t socket_type) {
  struct addrinfo hints;
  struct addrinfo *result, *rp = NULL;
  int status;

  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = socket_type;
  hints.ai_flags = 0;
  hints.ai_protocol = 0;

  // Address resolution.
  status = getaddrinfo(host, NULL, &hints, &result);
  if (0 != status) {
    return IOTC_BSP_IO_NET_STATE_ERROR;
  }

  for (rp = result; rp != NULL; rp = rp->ai_next) {
    *iotc_socket = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
    if (-1 == *iotc_socket) continue;

    // Set the socket to be non-blocking.
    const int flags = fcntl(*iotc_socket, F_GETFL);
    if (-1 == fcntl(*iotc_socket, F_SETFL, flags | O_NONBLOCK)) {
      freeaddrinfo(result);
      return IOTC_BSP_IO_NET_STATE_ERROR;
    }

    switch (rp->ai_family) {
      case AF_INET6:
        ((struct sockaddr_in6*)(rp->ai_addr))->sin6_port = htons(port);
        break;
      case AF_INET:
        ((struct sockaddr_in*)(rp->ai_addr))->sin_port = htons(port);
        break;
      default:
        return IOTC_BSP_IO_NET_STATE_ERROR;
        break;
    }

    // Attempt to connect.
    status = connect(*iotc_socket, rp->ai_addr, rp->ai_addrlen);

    if (-1 != status) {
      freeaddrinfo(result);
      return IOTC_BSP_IO_NET_STATE_OK;
    } else {
      if (EINPROGRESS == errno) {
        freeaddrinfo(result);
        return IOTC_BSP_IO_NET_STATE_OK;
      } else {
        close(*iotc_socket);
      }
    }
  }
  freeaddrinfo(result);
  return IOTC_BSP_IO_NET_STATE_ERROR;
}`

**Comment by sarasini** [comment]
Thank you very much @kangbudz, it works!

**Comment by shahpiyushv** [comment]
Sorry for the delay. iot-device-sdk-embedded-c has now been updated to 1.0.2.
