### ISSUE TITLE
Unable to send/receive MQTT during HTTPS OTA download (CA-84)

### ISSUE THREAD

**Issue by msn444** [espressif/esp-google-iot#15]
I am unable to send or receive MQTT during OTA downloads using the ESP-IDF HTTPS OTA library. MQTT transactions continue as soon as the OTA session closes.

Am I hitting a limit to the number of simultaneous connections allowed?

**Comment by shahpiyushv** [comment]
@msn444 hitting a limit to the number of simultaneous connections allowed seems unlikely. Can you check the priority of the threads? It could be possible that the OTA thread is blocking the mqtt thread.

**Comment by msn444** [comment]
Awesome, you're exactly right. I was actually performing the OTA transfer inside the MQTT subscription callback. Moved it to its own task and problem solved. Thanks!
