### ISSUE TITLE
  [Compilation Error] Unknown CMake command "register_component". (CA-45)

### ISSUE THREAD

**Issue by kangbudz** [espressif/esp-google-iot#7]
I have use esp-idf ver 3.3-rc. and my other projects is compiled well. But when i try to build this sample of google iot, i just get build error related with cmake component. currently use ubuntu 18.04 as build environtment. even run **idf.py menuconfig** also got similar issue.
Whats may wrong with my esp-idf setup related wth this google iot sample app?
Did i miss something?i clone this repo use --recursive option .
Below is my build output :
`budipras@Budi-X456URK:~/esp/esp32-project/esp32-google-iot/esp-google-iot$ idf.py app
Checking Python dependencies...
Python requirements from /home/budipras/esp/esp-idf/requirements.txt are satisfied.
Running cmake in directory /home/budipras/esp/esp32-project/esp32-google-iot/esp-google-iot/build
Executing "cmake -G 'Unix Makefiles' -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized /home/budipras/esp/esp32-project/esp32-google-iot/esp-google-iot"...
Warn about uninitialized values.
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:56 (register_component):
  Unknown CMake command "register_component".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/budipras/esp/esp32-project/esp32-google-iot/esp-google-iot/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1
`

**Comment by kangbudz** [comment]
i dont know what happen, but now try to recompile and everything goes fine.
so i close this
` budipras@Budi-X456URK:~/esp/esp32-project/esp32-google-iot/esp-google-iot/examples/smart_outlet$ idf.py app
Checking Python dependencies...
Python requirements from /home/budipras/esp/esp-idf/requirements.txt are satisfied.
Running make in directory /home/budipras/esp/esp32-project/esp32-google-iot/esp-google-iot/examples/smart_outlet/build
Executing "make -j 6 app"...
[  0%] Built target partition_table
[  0%] Built target dummy_main_src
[  0%] Built target idf_component_log
[  1%] Built target idf_component_heap
[  1%] Built target idf_component_main
[  3%] Built target idf_component_soc
`

**Comment by eercanayar** [comment]
Do you have any workaround about this? I'm having the exact same.

**Comment by marchanderic44** [comment]
I got the same error message. Did you find a solution?

**Comment by shahpiyushv** [comment]
I just tried the following and it worked for me

1. Set my esp-idf to v3.3.1 (since the original issue says this)
2. Synchronised the esp-idf submodules using `git submodule update --init --recursive`
3. Cloned esp-google-iot in a separate folder using the `git clone --recursive https://github.com/espressif/esp-google-iot.git`
4. `$ cd esp-google-iot/examples/smart_outlet`
5. `$ idf.py build`

This worked fine for me. I even switched the esp-idf branch to master and tried the same. It worked even there.

**Comment by shahpiyushv** [comment]
Just to add, deleting the build/ folder and sdkconfig file before re-compiling generally helps solve many issues.

**Comment by Bhavin8895** [comment]
I have use esp-idf ver 3.3-rc. and my other projects are compiled well. But when I try to build this sample of 
esp32-camera, I just get a build error related to the CMake component. currently use Linux Mint 20.1 Cinnamon as build environment.
Adding "set-target"'s dependency "fullclean" to list of commands with default set of options.
Executing action: fullclean
Executing action: set-target
Set Target to: esp32, new sdkconfig created. Existing sdkconfig renamed to sdkconfig.old.
Running cmake in directory /home/bhavin/esp/esp32-camera-master/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DIDF_TARGET=esp32 -DCCACHE_ENABLE=0 /home/bhavin/esp/esp32-camera-master"...
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:35 (register_component):
  Unknown CMake command "register_component".


-- Configuring incomplete, errors occurred!
See also "/home/bhavin/esp/esp32-camera-master/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1

after this, I use to remove the build/ folder and sdkconfig  file and I get 

Executing action: all (aliases: build)
Running ninja in directory /home/bhavin/esp/esp32-camera-master/build
Executing "ninja all"...
ninja: no work to do.
Done

**Comment by shahpiyushv** [comment]
@Bhavin8895 , was this comment meant for some other project, probably [this](https://github.com/espressif/esp32-camera/issues)?

**Comment by Bhavin8895** [comment]
I get the same error "register_component".
